#!/usr/bin/env zsh

# Source zplug
source $HOME/.zplug/init.zsh

zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search"
zplug "modules/directory", from:prezto
zplug "modules/history", from:prezto
zplug "modules/osx", from:prezto
zplug "modules/ssh", from:prezto
zplug "modules/tmux", from:prezto
zplug "modules/utility", from:prezto
zplug "modules/git", from:prezto
zplug "modules/homebrew", from:prezto
zplug "modules/node", from:prezto
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme

zplug load

